---
title: "3-redlining_la_notebook"
author: "Claire Morton"
date: "2/12/2021"
output: html_document
---

```{r setup, include=FALSE}
source("../../code/0-setup/1-setup.R")
```

```{r data_input, include=FALSE}
cal_counties <- st_read("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/raw/uscensus/admin_shp/CA_counties.shp") %>%
  st_transform(crs_nad83)
holc <- st_read("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/raw/u_richmond/mapping_inequality/shapefile/holc_ad_data.shp") %>%
  filter(state == "CA")

# LA data
holc_la <- holc %>% filter(city == "Los Angeles")
la_county <- cal_counties %>%
  filter(NAME == "Los Angeles")

shapefile_2009 <- read_sf("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/raw/uscensus/acs/2009/2009_BlockGroups") %>%
  select(5, 13) %>%
  st_intersection(la_county) %>%
  select(1, 19) %>%
  st_buffer(dist = 0.0)

shapefile_2014 <- read_sf("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/raw/uscensus/acs/2014/2014_BlockGroups") %>%
  select(5, 13) %>%
  st_intersection(la_county) %>%
  select(1, 19) %>%
  st_buffer(dist = 0.0)

shapefile_2019 <- read_sf("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/raw/uscensus/acs/2019/2019_BlockGroups") %>%
  select(5, 13) %>%
  st_intersection(la_county) %>%
  select(1, 19) %>%
  st_buffer(dist = 0.0)

# rename columns appropriately
shapefile_2009 <- shapefile_2009 %>%
  rename(GEOID = BKGPIDFP00)
shapefile_2009$GEOID <- paste("15000US", shapefile_2009$GEOID, sep="")

shapefile_2014$GEOID <- paste("15000US", shapefile_2014$GEOID, sep="")

shapefile_2019$GEOID <- paste("15000US", shapefile_2019$GEOID, sep="")

holc_2009 <- read_rds("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/processed/holc_2009_apportioned.rds")
holc_2014 <- read_rds("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/processed/holc_2014_apportioned.rds")
holc_2019 <- read_rds("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/processed/holc_2019_apportioned.rds")

acs_2009 <- read_csv("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/processed/acs_joined_2009.csv")
acs_2014 <- read_csv("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/processed/acs_joined_2014.csv")
acs_2019 <- read_csv("/Users/clairemorton/Documents/2020Research/cal-drilling-disparities/data/processed/acs_joined_2019.csv")
```

```{r include=FALSE}
combined_2009_geom <- merge(holc_2009, shapefile_2009, by = "GEOID")
combined_2014_geom <- merge(holc_2014, shapefile_2014, by = "GEOID")
combined_2019_geom <- merge(holc_2019, shapefile_2019, by = "GEOID")

combined_2009 <- merge(holc_2009, acs_2009, by = "GEOID")
combined_2014 <- merge(holc_2014, acs_2014, by = "GEOID")
combined_2019 <- merge(holc_2019, acs_2019, by = "GEOID")

```

Visualization of 2009, 2014, 2019 block groups showing areal apportionment appears to have worked correctly.
```{r echo = FALSE}
library(leaflet)
options(viewer = NULL)
pal <- colorNumeric("plasma", domain = NULL, reverse = FALSE)

ggplot (combined_2009_geom, aes(geometry = geometry)) +
  geom_sf(data = combined_2009_geom, fill = pal(combined_2009_geom$avg_score), lwd = 0)
ggplot (combined_2014_geom, aes(geometry = geometry)) +
  geom_sf(data = combined_2014_geom, fill = pal(combined_2014_geom$avg_score), lwd = 0)
ggplot (combined_2019_geom, aes(geometry = geometry)) +
  geom_sf(data = combined_2019_geom, fill = pal(combined_2019_geom$avg_score), lwd = 0)
ggplot (combined_2009_geom, aes(geometry = geometry)) +
  geom_sf(data = combined_2009_geom, fill = pal(combined_2009_geom$cent_score), lwd = 0)
ggplot (combined_2014_geom, aes(geometry = geometry)) +
  geom_sf(data = combined_2014_geom, fill = pal(combined_2014_geom$cent_score), lwd = 0)
ggplot (combined_2019_geom, aes(geometry = geometry)) +
  geom_sf(data = combined_2019_geom, fill = pal(combined_2019_geom$cent_score), lwd = 0)
```

I'm not sure how to most effectively show this data -- the graph below (2014, 762m well overlap) cuts out all block groups that don't overlap with HOLC outlines but there are a lot of block groups with no wells so it's hard to see any trends that might be there. Suggestions appreciated!
```{r echo=FALSE}
ggplot (combined_2014, aes(x = avg_score, y = buffer_overlap_762m))+
  geom_jitter(width = .1, height = .1) +
  geom_smooth(method='loess')
```


```{r echo=FALSE}
combined_2009$cent_score <- as.factor(combined_2009$cent_score)
ggplot (combined_2009, aes(x = cent_score, y = buffer_overlap_3km, fill = cent_score))+
  geom_violin(width = 1)+
  geom_boxplot(width=0.2, color="black", alpha=0.2)
  #geom_smooth(method = 'loess')
  
  
```




